name = "izuran-store"
main = "src/worker.js"
compatibility_date = "2026-09-20"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "izuran-db"
database_id = "00000000-00000006-000050ec-981b2ddd4b704e635ea08d090ac6fd70"