name = "izuran-store"
main = "src/worker.js"
compatibility_date = "2026-09-20"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "izuran-db"
database_id = "95f83d04-f503-4aa5-aee4-1292bd15925f"